editor/urls.py
# -*- coding: utf-8 -*-
# @Author: MarkJiYuan
# @Date:   2019-06-28 23:07:23
# @Last Modified by:   MarkJiYuan
# @email: zhengjiy16@163.com
# @Last Modified time: 2019-06-28 23:22:47
# @Abstract: 

from django.urls import path
from . import views

app_name = 'editor'
urlpatterns = [
	path('', views.index, name='index'),
	path('pending/', views.pending, name='pending'),
	path('profile/<int:idArticle>/<int:submit_times>', views.profile, name='profile'),
	path('download/<int:idArticle>/<int:submit_times>', views.download, name='download'),
	path('processing/', views.processing, name='processing'),
	path('finish/<int:idArticle>/<int:submit_times>', views.finish, name='finish'),
	path('done/', views.done, name='done')
]

editorinchief/urls.py
# -*- coding: utf-8 -*-
# @Author: MarkJiYuan
# @Date:   2019-06-28 23:16:56
# @Last Modified by:   MarkJiYuan
# @email: zhengjiy16@163.com
# @Last Modified time: 2019-07-16 22:48:38
# @Abstract: 

from django.urls import path
from . import views

app_name = 'editorinchief'
urlpatterns = [
	path('', views.index, name='index'),
	path('pending', views.pending, name='pending'),
	path('profile/<int:idArticle>/<int:submit_times>/', views.profile, name='profile'),
	path('processing/', views.processing, name='processing'),
	path('processing/choose_ae/<int:idArticle>/<int:submit_times>/', views.choose_ae, name='choose_ae'),
	path('all_articles', views.all_articles, name='all_articles'),
	path('download_paper/<int:idArticle>/<int:submit_times>', views.download_paper, name='download_paper'),
	path('admin_editor/', views.admin_editor, name='admin_editor'),
	path('admin_editor/new_editor', views.new_editor, name='new_editor'),
	path('admin_editor/add_editor', views.add_editor, name='add_editor'),
	path('admin_ae/', views.admin_ae, name='admin_ae'),
	path('admin_ae/new_ae', views.new_ae, name='new_ae'),
	path('admin_ae/add_ae', views.add_ae, name='add_ae'),
	path('admin_reviewer/', views.admin_reviewer, name='admin_reviewer'),
	path('admin_reviewer/new_reviewer', views.new_reviewer, name='new_reviewer'),
	path('admin_reviewer/add_reviewer', views.add_reviewer, name='add_reviewer'),
	path('finish/<int:idArticle>/<int:submit_times>/', views.finish, name='finish'),
]

papersubmission/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('reviewer/', include('reviewer.urls')),
    path('AE/', include('associateeditor.urls')),
    path('EIC/', include('editorinchief.urls')),
    path('editor/', include('editor.urls')),
	path('submitter/', include('submitter.urls')),
	path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

editorinchief/models.py
from django.db import models

# Create your models here.

editorinchief/views.py
import os
import re
from django.shortcuts import render
from django.http import FileResponse
from paperdb.accept import Accept
from paperdb.load import Loader
from smtp.myemail import Email

def index(request):
	context = {}
	welcome = '欢迎您！主编' + request.session['username']
	return render(request, 'editorinchief/index.html', {
			'message': welcome,
		})

def processing(request):

	db = Accept()

	pre1 = '审阅状态2="大boss正审"'
	articles = db.accept(104, [pre1])
	articles = Loader.article(articles)[::-1]

	context = {
		'table_title': '大boss处理中',
		'papers': articles
	}

	return render(request, 'editorinchief/pending.html', context)

def all_articles(request):

	db = Accept()

	articles = db.accept(104, [])
	articles = Loader.article(articles)[::-1]

	context = {
		'table_title': '全部稿件',
		'papers': articles,
	}

	return render(request, 'editorinchief/all_articles.html', context)

def pending(request):

	db = Accept()

	pre1 = '审阅状态2="大boss待审"'
	articles = db.accept(104, [pre1])
	articles = Loader.article(articles)[::-1]

	pre1 = '审阅状态2="大boss待评论"'
	comment_articles = db.accept(104, [pre1])
	comment_articles = Loader.article(comment_articles)[::-1]

	articles = comment_articles + articles

	context = {
		'table_title': '大boss待处理',
		'papers': articles
	}

	return render(request, 'editorinchief/pending.html', context)

def profile(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	if paper.shen2 == '大boss待审':
		db.accept(119, [idArticle, submit_times])

	aes = db.accept(112, ['associateeditor'])
	aes = Loader.ae(aes)

	idAuthor = paper.author
	pre1 = 'id="' + idAuthor + '"'
	real_author = db.accept(122, [pre1])
	real_author = Loader.author(real_author)[0]
	paper.author = real_author.name

	context = {
		'paper': paper,
		'aes': aes,
	}

	if paper.shen2 in ['大boss待审', '大boss正审']:
		context['allow_select'] = True

	if paper.shen2 not in ['待处理', 'editor待审', 'editor正审', '待修改', '决定发表', '决定不录用', '已完成']:
		context['allow_comment'] = True
	else:
		context['current_eic'] = request.session['username']
		file_path = paper.path + 'eic_comment.txt'

		try:
			with open(file_path, 'r') as f:
				comment_eic = f.read()
		except Exception as e:
			comment_eic = "主编尚未评价"

		context['comment_eic'] = comment_eic

	if paper.aes != None:
		ae_account = paper.aes.split('/')[0]
		ae = db.accept(112, ['associateeditor', ae_account])
		ae = Loader.ae(ae)[0]
		current_ae = ae.name
		context['current_ae'] = current_ae

		file_path = paper.path + 'ae_' + ae_account + '_comment.txt'

		try:
			with open(file_path, 'r') as f:
				comment_ae = f.read()
		except Exception as e:
			comment_ae = "AE尚未评价"

		context['comment_ae'] = comment_ae

	if paper.reviewers != None:
		reviewer_account = paper.reviewers.split('/')[0]
		reviewer = db.accept(112, ['reviewer', reviewer_account])
		reviewer = Loader.reviewer(reviewer)[0]
		current_reviewer = reviewer.name
		context['current_reviewer'] = current_reviewer

		file_path = paper.path + 'reviewer_' + reviewer_account + '_comment.txt'

		try:
			with open(file_path, 'r') as f:
				comment_reviewer = f.read()
		except Exception as e:
			comment_reviewer = "Reviewer尚未评价"

		context['comment_reviewer'] = comment_reviewer


	return render(request, 'editorinchief/detail_eic.html', context)

def choose_ae(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	ae_account = request.POST['ae_account']

	db.accept(113, [ae_account, idArticle, submit_times])

	em = Email()
	email_context = {
		'sender_name': '迅波投审稿系统',
		'sender': 'zhengjiy16@163.com',
		'receiver_name': ae_account,
		'receiver': 'jinsh.16@sem.tsinghua.edu.cn',
		'subject': request.session['username'] + '：分配给了您新的文章',
		'html': '<h3>尊敬的责编：您好！有新的分配给您的投稿</h3><p>题目：' + paper.title + '</p>',
		'body': '系统自动通知',
		'attachments': [
		],
	}
	em.send_email()

	return render(request, 'editorinchief/index.html', {
			'message': '指派ae成功'
		})

def download_paper(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	for file_name in os.listdir(paper.path):
		answer = re.match(paper.title, file_name)
		if answer != None:
			file_path = paper.path + file_name
			break

	response = FileResponse(open(file_path, 'rb'))
	response['content_type'] = "application/octet-stream"
	response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)

	return response

def admin_editor(request):

	db = Accept()

	editors = db.accept(112, ['editor'])
	editors = Loader.editor(editors)

	context = {
		'table_title': 'editor人员列表',
		'editors': editors,
	}

	return render(request, 'editorinchief/list_editor.html', context)

def new_editor(request):
	context = {
		'form_name': '新增editor'
	}
	return render(request, 'editorinchief/info_editor.html', context)

def add_editor(request):

	db = Accept()

	account = request.POST['account']
	password = request.POST['password']
	role = 'editor'
	email_adr = request.POST['email_adr']
	name = request.POST['nickname']

	db.accept(110, [account, password, role, email_adr, name])

	editors = db.accept(112, ['editor'])
	editors = Loader.editor(editors)

	context = {
		'table_title': 'editor人员列表',
		'editors': editors,
		'message': '添加新editor成功',
	}

	return render(request, 'editorinchief/list_editor.html', context)

def admin_ae(request):

	db = Accept()

	aes = db.accept(112, ['associateeditor'])
	aes = Loader.ae(aes)

	context = {
		'table_title': 'ae人员列表',
		'aes': aes,
	}

	return render(request, 'editorinchief/list_ae.html', context)

def new_ae(request):

	context = {
		'form_name': '新增ae'
	}
	return render(request, 'editorinchief/info_ae.html', context)

def add_ae(request):

	db = Accept()

	account = request.POST['account']
	password = request.POST['password']
	role = 'associateeditor'
	email_adr = request.POST['email_adr']
	name = request.POST['nickname']
	institution = request.POST['institution']
	field = request.POST['field']

	db.accept(110, [account, password, role, email_adr, name, institution, field])

	aes = db.accept(112, ['associateeditor'])
	aes = Loader.ae(aes)

	context = {
		'table_title': 'ae人员列表',
		'aes': aes,
		'message': '添加新ae成功',
	}

	return render(request, 'editorinchief/list_ae.html', context)

def admin_reviewer(request):

	db = Accept()

	reviewers = db.accept(112, ['reviewer'])
	reviewers = Loader.reviewer(reviewers)

	context = {
		'table_title': 'reviewer人员列表',
		'reviewers': reviewers,
	}

	return render(request, 'editorinchief/list_reviewer.html', context)

def new_reviewer(request):

	context = {
		'form_name': '新增reviewer'
	}
	return render(request, 'editorinchief/info_reviewer.html', context)

def add_reviewer(request):

	db = Accept()

	account = request.POST['account']
	password = request.POST['password']
	role = 'reviewer'
	email_adr = request.POST['email_adr']
	name = request.POST['nickname']
	institution = request.POST['institution']
	field = request.POST['field']

	db.accept(110, [account, password, role, email_adr, name, institution, field])

	reviewers = db.accept(112, ['reviewer'])
	reviewers = Loader.reviewer(reviewers)

	context = {
		'table_title': 'reviewer人员列表',
		'reviewers': reviewers,
		'message': '添加新reviewer成功',
	}

	return render(request, 'editorinchief/list_reviewer.html', context)

def finish(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	comment = request.POST['comment']
	judgement = request.POST['judgement']

	comment_path = paper.path + 'eic_comment.txt'
	with open(comment_path, 'w') as f:
		f.write(comment)

	db.accept(120, [idArticle, submit_times, judgement])

	em = Email()
	if judgement == '待修改':
		email_context = {
			'sender_name': '迅波投审稿系统',
			'sender': 'zhengjiy16@163.com',
			'receiver_name': paper.account,
			'receiver': 'jinsh.16@sem.tsinghua.edu.cn',
			'subject': request.session['username'] + '：您的投稿动态',
			'html': '<h3>尊敬的投稿人：您好！您的文章已通过这一轮审核，请继续修改</h3><p>题目：' + paper.title + '</p>',
			'body': '系统自动通知',
			'attachments': [
			],
		}
	if judgement == '决定发表':
		email_context = {
			'sender_name': '迅波投审稿系统',
			'sender': 'zhengjiy16@163.com',
			'receiver_name': paper.account,
			'receiver': 'jinsh.16@sem.tsinghua.edu.cn',
			'subject': request.session['username'] + '：您的投稿动态',
			'html': '<h3>尊敬的投稿人：您好！您的文章已通过审核，决定发表了！</h3><p>题目：' + paper.title + '</p>',
			'body': '系统自动通知',
			'attachments': [
			],
		}
	if judgement == '决定不发表':
		email_context = {
			'sender_name': '迅波投审稿系统',
			'sender': 'zhengjiy16@163.com',
			'receiver_name': paper.account,
			'receiver': 'jinsh.16@sem.tsinghua.edu.cn',
			'subject': request.session['username'] + '：您的投稿动态',
			'html': '<h3>尊敬的投稿人：您好！很遗憾您的文章没能入选，请继续努力！</h3><p>题目：' + paper.title + '</p>',
			'body': '系统自动通知',
			'attachments': [
			],
		}
	em.send_email()


	return render(request, 'editorinchief/index.html', {
			'message': '审查结束，可在已完成中进行查看'
		})

editorinchief/templates/editorinchief/all_articles.html
{% extends 'list.html' %}

{% block title %}
	{{ table_title }}
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'editorinchief:index' %}">主编个人主页</a>
{% endblock %}

{% block info %}
	主编{{ request.session.username }}
{% endblock %}

{% block content %}

	<ul>
		<li><a href="{% url 'editorinchief:pending' %}">待处理</a></li>
		<li><a href="{% url 'editorinchief:processing' %}">处理中</a></li>
		<li><a href="{% url 'editorinchief:all_articles' %}">全部稿件</a></li>
	</ul>
	<ul>
		<li><a href="{% url 'editorinchief:admin_editor' %}">editor管理</a></li>
		<li><a href="{% url 'editorinchief:admin_ae' %}">ae管理</a></li>
		<li><a href="{% url 'editorinchief:admin_reviewer' %}">reviewer管理</a></li>
	</ul>
{% endblock %}


{% block t_head %}
	<tr>
		<td>id</td>
		<td>投稿次数</td>
		<td>题目</td>
		<td>提交时间</td>
		<td>审阅状态2</td>
	</tr>
{% endblock %}

{% block paper_url %}
	{% for paper in papers %}
		<tr>
			<td>{{ paper.idArticle }}</td>
			<td>{{ paper.submit_times }}</td>
			<td><a href="{% url 'editorinchief:profile' paper.idArticle paper.submit_times %}">{{ paper.title }}</a></td>
			<td>{{ paper.submit_time }}</td>
			<td>{{ paper.shen2 }}</td>
		</tr>
	{% endfor %}
{% endblock %}

editorinchief/templates/editorinchief/detail_eic.html
{% extends 'paperprofile.html' %}

{% block title %}
	稿件详情
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'editorinchief:index' %}"><span id="profile0-tab-span">主编个人主页</span></a>
{% endblock %}

{% block info %}
	主编{{ request.session.username }}
{% endblock %}

{% block content %}

	<ul>
		<li><a href="{% url 'editorinchief:pending' %}">待处理</a></li>
		<li><a href="{% url 'editorinchief:processing' %}">处理中</a></li>
		<li><a href="{% url 'editorinchief:all_articles' %}">全部稿件</a></li>
	</ul>
	<ul>
		<li><a href="{% url 'editorinchief:admin_editor' %}">editor管理</a></li>
		<li><a href="{% url 'editorinchief:admin_ae' %}">ae管理</a></li>
		<li><a href="{% url 'editorinchief:admin_reviewer' %}">reviewer管理</a></li>
	</ul>
{% endblock %}

{% block status %}
	{{ paper.shen2 }}
{% endblock %}

{% block more_information %}

	{% if current_eic %}

		<style type="text/css">
			.detail {
				min-height: 800px;
			}
		</style>

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>主编{{ current_eic }}评价内容</a>
	                </div>
				</div>
			</div>
			<div class="cont">
				<p>{{ comment_eic }}</p>
			</div>
		</div>

	{% endif %}

	{% if current_ae %}

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>AE{{ current_ae }}评价内容</a>
	                </div>
				</div>
			</div>
			<div class="cont">
				<p>{{ comment_ae }}</p>
			</div>
		</div>

	{% endif %}

	{% if current_reviewer %}

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>Reviewer{{ current_reviewer }}评价内容</a>
	                </div>
				</div>
			</div>
			<div class="cont">
				<p>{{ comment_reviewer }}</p>
			</div>
		</div>

	{% endif %}

	{% if allow_select %}

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>选择AE</a>
	                </div>
				</div>
			</div>
			<div class="cont" style="padding-left: 50px;">
				<form method="post" id="selectae-form">
					{% csrf_token %}
					<select name="ae_account">
						{% for ae in aes %}
							<option value="{{ ae.account }}">{{ ae.name }}, {{ ae.field }}</option>
						{% endfor %}
					</select>
				</form>
				<button class="button_1" onclick="distribute()" style="margin-top: 10px;">确定分配</button>
			</div>
			
		</div>
	{% endif %}

	{% if allow_comment %}

		<div class="info_section">
	        <div class="notice">
	            <div class="tit">
	                <div class="crumb clearfix fl">
	                    <a>审阅意见</a>
	                </div>
	            </div>
	        </div>
	        <div class="cont">
	            <form action="{% url 'editorinchief:finish' paper.idArticle paper.submit_times %}" method="post" id="comment-form">
	            	{% csrf_token %}
	            	<textarea name="comment" class="text_area"></textarea>

					<div class="notice">
						<div class="tit">
							<div class="crumb clearfix fl">
			                    <a>评阅结果</a>
			                </div>
						</div>
					</div>

					<div class="cont" style="margin-left: 50px;">
						<label class="mycheck">
		                    <input type="radio" name="judgement" value="待修改" checked="checked"><i></i>待修改
		                </label>
		                <label class="mycheck">
		                    <input type="radio" name="judgement" value="决定发表"><i></i>决定发表
		                </label>
		                <label class="mycheck">
		                    <input type="radio" name="judgement" value="决定不录用"><i></i>决定不录用
		                </label>
					</div>
					<button type="submit" class="button_1" style="margin-top: 20px;margin-left: 50px;margin-bottom: 30px;">完成评审</button>
					
	            </form>
	        </div>
	    </div>
	
	{% endif %}


{% endblock %}

{% block script %}
	<script type="text/javascript">
		function distribute() {
			var form = document.getElementById('selectae-form')
			form.action = "{% url 'editorinchief:choose_ae' paper.idArticle paper.submit_times %}"
			form.submit()
		}
	</script>

{% endblock %}

editorinchief/templates/editorinchief/info_ae.html
{% extends 'newitem.html' %}

{% block title %}
	新增ae
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'editorinchief:index' %}">主编个人主页</a>
{% endblock %}

{% block info %}
	主编{{ request.session.username }}
{% endblock %}


{% block content %}

	<ul>
		<li><a href="{% url 'editorinchief:pending' %}">待处理</a></li>
		<li><a href="{% url 'editorinchief:processing' %}">处理中</a></li>
		<li><a href="{% url 'editorinchief:all_articles' %}">全部稿件</a></li>
	</ul>
	<ul>
		<li><a href="{% url 'editorinchief:admin_editor' %}">editor管理</a></li>
		<li><a href="{% url 'editorinchief:admin_ae' %}">ae管理</a></li>
		<li><a href="{% url 'editorinchief:admin_reviewer' %}">reviewer管理</a></li>
	</ul>
{% endblock %}


{% block form %}
	<form action="{% url 'editorinchief:add_ae' %}" method="post" id="new-ae-form" class="newitem_form">
		{% csrf_token %}
		<div class="input_box">
            <div class="left_text"><i class="red">*</i>姓名</div>
            <div class="right_input">
                <input type="text" name="nickname" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

        <div class="input_box">
            <div class="left_text"><i class="red">*</i>机构</div>
            <div class="right_input">
                <input type="text" name="institution" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

        <div class="input_box">
            <div class="left_text"><i class="red">*</i>领域</div>
            <div class="right_input">
                <input type="text" name="field" required="" value="" autocomplete="off" placeholder="不同领域名用空格分割" aria-required="true">
            </div>
        </div>

        <div class="input_box">
            <div class="left_text"><i class="red">*</i>用户名</div>
            <div class="right_input">
                <input type="text" name="account" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

        <div class="input_box">
            <div class="left_text"><i class="red">*</i>密码</div>
            <div class="right_input">
                <input type="text" name="password" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

		<div class="input_box">
            <div class="left_text"><i class="red">*</i>邮箱</div>
            <div class="right_input">
                <input type="text" name="email_adr" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>
        

        <div class="sub_back">
        	<button type="button" class="do_submit" onclick="add_new_ae()">确认添加</button>
        	<button type="button" class="return_btn" onclick="goback()">返回</button>
        </div>
	</form>

{% endblock %}


{% block script %}
	<script type="text/javascript">
		function add_new_ae() {
			var form = document.getElementById('new-ae-form');
			form.submit();
		}
		function goback() {
			window.history.go(-1);
		}
	</script>
{% endblock %}

editorinchief/templates/editorinchief/info_editor.html
{% extends 'newitem.html' %}

{% block title %}
	新增editor
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'editorinchief:index' %}">主编个人主页</a>
{% endblock %}

{% block info %}
	主编{{ request.session.username }}
{% endblock %}


{% block content %}

	<ul>
		<li><a href="{% url 'editorinchief:pending' %}">待处理</a></li>
		<li><a href="{% url 'editorinchief:processing' %}">处理中</a></li>
		<li><a href="{% url 'editorinchief:all_articles' %}">全部稿件</a></li>
	</ul>
	<ul>
		<li><a href="{% url 'editorinchief:admin_editor' %}">editor管理</a></li>
		<li><a href="{% url 'editorinchief:admin_ae' %}">ae管理</a></li>
		<li><a href="{% url 'editorinchief:admin_reviewer' %}">reviewer管理</a></li>
	</ul>
	
{% endblock %}


{% block form %}
	<form action="{% url 'editorinchief:add_editor' %}" method="post" id="new-editor-form" class="newitem_form">
		{% csrf_token %}
		<div class="input_box">
            <div class="left_text"><i class="red">*</i>姓名</div>
            <div class="right_input">
                <input type="text" name="nickname" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

        <div class="input_box">
            <div class="left_text"><i class="red">*</i>用户名</div>
            <div class="right_input">
                <input type="text" name="account" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

        <div class="input_box">
            <div class="left_text"><i class="red">*</i>密码</div>
            <div class="right_input">
                <input type="text" name="password" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>

		<div class="input_box">
            <div class="left_text"><i class="red">*</i>邮箱</div>
            <div class="right_input">
                <input type="text" name="email_adr" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
            </div>
        </div>
        

        <div class="sub_back">
        	<button type="button" class="do_submit" onclick="add_new_editor()">确认添加</button>
        	<button type="button" class="return_btn" onclick="goback()">返回</button>
        </div>
	</form>

{% endblock %}

{% block script %}
	<script type="text/javascript">
		function add_new_editor() {
			var form = document.getElementById('new-editor-form');
			form.submit();
		}
		function goback() {
			window.history.go(-1);
		}
	</script>
{% endblock %}

editorinchief/templates/editorinchief/list_ae.html
{% extends 'list.html' %}

{% block title %}
	{{ table_title }}
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'editorinchief:index' %}">主编个人主页</a>
{% endblock %}

{% block info %}
	主编{{ request.session.username }}
{% endblock %}

{% block content %}

	<ul>
		<li><a href="{% url 'editorinchief:pending' %}">待处理</a></li>
		<li><a href="{% url 'editorinchief:processing' %}">处理中</a></li>
		<li><a href="{% url 'editorinchief:all_articles' %}">全部稿件</a></li>
	</ul>
	<ul>
		<li><a href="{% url 'editorinchief:admin_editor' %}">editor管理</a></li>
		<li><a href="{% url 'editorinchief:admin_ae' %}">ae管理</a></li>
		<li><a href="{% url 'editorinchief:admin_reviewer' %}">reviewer管理</a></li>
	</ul>
{% endblock %}

{% block new_item %}
	<div class="new-ae">
		<button onclick="new_ae()" class="new_item">新增ae</button>
	</div>
{% endblock %}

{% block t_head %}
	<tr>
		<td>姓名</td>
		<td>账户</td>
		<td>机构</td>
		<td>领域</td>
	</tr>
{% endblock %}

{% block paper_url %}
	{% for ae in aes %}
		<tr>
			<td>{{ ae.name }}</td>
			<td>{{ ae.account }}</td>
			<td>{{ ae.institution }}</td>
			<td>{{ ae.field }}</td>
		</tr>
	{% endfor %}
{% endblock %}

{% block script %}
	<script type="text/javascript">
		function new_ae() {
			window.location.href = "{% url 'editorinchief:new_ae' %}"
		}
	</script>
{% endblock %}