editor/urls.py
# -*- coding: utf-8 -*-
# @Author: MarkJiYuan
# @Date:   2019-06-28 23:07:23
# @Last Modified by:   MarkJiYuan
# @email: zhengjiy16@163.com
# @Last Modified time: 2019-06-28 23:22:47
# @Abstract: 

from django.urls import path
from . import views

app_name = 'editor'
urlpatterns = [
	path('', views.index, name='index'),
	path('pending/', views.pending, name='pending'),
	path('profile/<int:idArticle>/<int:submit_times>', views.profile, name='profile'),
	path('download/<int:idArticle>/<int:submit_times>', views.download, name='download'),
	path('processing/', views.processing, name='processing'),
	path('finish/<int:idArticle>/<int:submit_times>', views.finish, name='finish'),
	path('done/', views.done, name='done')
]

papersubmission/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('reviewer/', include('reviewer.urls')),
    path('AE/', include('associateeditor.urls')),
    path('EIC/', include('editorinchief.urls')),
    path('editor/', include('editor.urls')),
	path('submitter/', include('submitter.urls')),
	path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

submitter/urls.py
from django.urls import path
from . import views

app_name = 'submitter'
urlpatterns = [
	path('index/', views.index, name='index'),
	path('submit/', views.submit, name='submit'),
	path('submit/upload_file', views.upload_file, name='upload_file'),
	path('submit/save_file', views.save_file, name='save_file'),
	path('saved', views.saved, name='saved'),
	path('submitted/', views.submitted, name='submitted'),
	path('profile/<int:idArticle>/<int:submit_times>', views.profile, name='profile'),
	path('dosubmit/<int:idArticle>/<int:submit_times>', views.dosubmit, name='dosubmit'),
	path('deletepaper/<int:idArticle>/<int:submit_times>', views.deletepaper, name='deletepaper'),
	path('submittedprofile/<int:idArticle>/<int:submit_times>', views.submitted_profile, name='submitted_profile'),
	path('resubmit/<int:idArticle>/<int:submit_times>', views.resubmit, name='resubmit'),
	path('', views.index, name='index'),
]

submitter/models.py
from django.db import models

class Submission(models.Model):
	papername = models.CharField(max_length=100)
	author = models.CharField(max_length=30)
	abstract = models.CharField(max_length=300)
	submit_date = models.DateTimeField('date submitted', auto_now_add=True)
	fileurl = models.CharField(max_length=200)

	def __str__(self):
		return self.papername

submitter/views.py
import os
from django.shortcuts import render, redirect
from paperdb.accept import Accept
from paperdb.load import Loader

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPLOAD_DIR = BASE_DIR + '/upload/'

def index(request):
	context = {}
	welcome = '欢迎您！投稿人' + request.session['username']
	return render(request, 'submitter/index.html', {
			'message': welcome
		})

def submit(request):
	context = {
		'form_name': '新增投稿'
	}
	return render(request, 'submitter/submit.html', context)

def upload_file(request):

	is_second_submit = request.POST['is_second_submit']

	# 获取附件，判断是否为空
	myfile = request.FILES.get("myfile", None)

	if not myfile:
		if not is_second_submit:
			return render(request, 'submitter/submit.html', {
					'message': '没有提交附件!',
					'form_name': '新增投稿'
				})
		else:
			return render(request, 'submitter/submit.html', {
					'message': '没有提交附件!',
					'form_name': '二审投稿'
				})

	extension = os.path.splitext(myfile.name)[1]

	db = Accept()

	account = request.session['username']
	title = request.POST['title']
	author = request.POST['author']
	abstract = request.POST['abstract']
	keywords = request.POST['keywords']

	if not is_second_submit:

		# 将附件进行存储，记录fileurl, 目前仅支持单个附件
		dir_name = title
		path = UPLOAD_DIR + dir_name + '_ver1/'
		
		try:
			os.mkdir(path)
			fileurl = path + title + extension
			with open(fileurl, 'wb+') as f:
				for chunk in myfile.chunks():
					f.write(chunk)
		except Exception as e:
			print(e)
			return render(request, 'submitter/submit.html', {
					'message': '文章名称重复！请检查后重新投稿',
					'form_name': '新增投稿'
				})

		db.accept(103, [account, title, abstract, keywords, [[author, '无名机构', '破烂邮箱']], path, 1])

		pre1 = '附件路径="' + path + '"'
		paper = db.accept(104, [pre1])
		paper = Loader.article(paper)[0]

		db.accept(107, [paper.idArticle, paper.submit_times])

		return render(request, 'submitter/index.html', {
				'message': '提交成功，不可再修改，可在过往投稿中查看审阅状态'
			})
	else:
		old_idArticle = request.POST['old_idArticle']
		old_submit_times = request.POST['old_submit_times']
		old_path = request.POST['old_path']
		version = '_ver' + str(old_submit_times)
		new_path = old_path.split(version)[0] + '_ver' + str(int(old_submit_times) + 1) + '/'

		
		try:
			os.mkdir(new_path)
			fileurl = new_path + title + extension
			with open(fileurl, 'wb+') as f:
				for chunk in myfile.chunks():
					f.write(chunk)
		except Exception as e:
			print(e)
			return render(request, 'submitter/submit.html', {
					'message': '文章名称重复！请检查后重新投稿',
					'form_name': '二审投稿'
				})

		db.accept(121, [old_idArticle, old_submit_times, account, title, abstract, keywords, [[author, '无名机构', '破烂邮箱']], new_path, 1])

		pre1 = '附件路径="' + new_path + '"'
		paper = db.accept(104, [pre1])
		paper = Loader.article(paper)[0]

		db.accept(107, [paper.idArticle, paper.submit_times])

		return render(request, 'submitter/index.html', {
				'message': '二审提交成功，不可再修改，可在过往投稿中查看审阅状态'
			})


def save_file(request):

	is_second_submit = request.POST['is_second_submit']

	# 获取附件，判断是否为空
	myfile = request.FILES.get("myfile", None)

	if not myfile:
		if not is_second_submit:
			return render(request, 'submitter/submit.html', {
					'message': '没有提交附件!',
					'form_name': '新增投稿'
				})
		else:
			return render(request, 'submitter/submit.html', {
					'message': '没有提交附件!',
					'form_name': '二审投稿'
				})

	extension = os.path.splitext(myfile.name)[1]

	db = Accept()

	account = request.session['username']
	title = request.POST['title']
	author = request.POST['author']
	abstract = request.POST['abstract']
	keywords = request.POST['keywords']

	if not is_second_submit:
		# 将附件进行存储，记录fileurl, 目前仅支持单个附件
		dir_name = title
		path = UPLOAD_DIR + dir_name + '_ver1/'

		try:
			os.mkdir(path)
			fileurl = path + title + extension
			with open(fileurl, 'wb+') as f:
				for chunk in myfile.chunks():
					f.write(chunk)
		except Exception as e:
			print(e)
			return render(request, 'submitter/submit.html', {
					'message': '文章名称重复！请检查后重新投稿',
					'form_name': '新增投稿'
				})


		db.accept(103, [account, title, abstract, keywords, [[author, '无名机构', '破烂邮箱']], path, 1])

		return render(request, 'submitter/index.html', {
				'message': '保存成功，可在“保存尚未提交”中进行修改或正式提交'
			})
	else:
		old_idArticle = request.POST['old_idArticle']
		old_submit_times = request.POST['old_submit_times']
		old_path = request.POST['old_path']
		version = '_ver' + str(old_submit_times)
		new_path = old_path.split(version)[0] + '_ver' + str(int(old_submit_times) + 1) + '/'

		try:
			os.mkdir(new_path)
			fileurl = new_path + title + extension
			with open(fileurl, 'wb+') as f:
				for chunk in myfile.chunks():
					f.write(chunk)
		except Exception as e:
			print(e)
			return render(request, 'submitter/submit.html', {
					'message': '文章名称重复！请检查后重新投稿',
					'form_name': '二审投稿'
				})

		db.accept(121, [old_idArticle, old_submit_times, account, title, abstract, keywords, [[author, '无名机构', '破烂邮箱']], new_path, 1])

		return render(request, 'submitter/index.html', {
				'message': '二审保存成功，可在“保存尚未提交”中进行修改或正式提交'
			})


def saved(request):
	db = Accept()

	pre1 = 'account="' + request.session['username'] + '"'
	pre2 = 'visible=1'
	pre3 = 'changeable=1'
	articles = db.accept(104, [pre1, pre2, pre3])
	articles = Loader.article(articles)[::-1]

	context = {
		'table_title': '保存尚未提交',
		'papers': articles,
	}

	return render(request, 'submitter/saved.html', context)

def submitted(request):
	db = Accept()

	pre1 = 'account="' + request.session['username'] + '"'
	pre2 = 'visible=1'
	pre3 = 'changeable=0'
	articles = db.accept(104, [pre1, pre2, pre3])
	articles = Loader.article(articles)[::-1]

	for article in articles:
		if article.shen1 == '已完成':
			article.shen1 = article.shen2

	context = {
		'table_title': '已提交稿件',
		'papers': articles,
	}

	return render(request, 'submitter/submitted.html', context)


def profile(request, idArticle, submit_times):
	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'

	this_article = db.accept(104, [pre1, pre2])
	this_article = Loader.article(this_article)[0]

	idAuthor = this_article.author
	pre1 = 'id="' + idAuthor + '"'
	real_author = db.accept(122, [pre1])
	real_author = Loader.author(real_author)[0]
	this_article.author = real_author.name

	context = {
		'paper': this_article,
		'allow_change': True,
		'form_name': '稿件详情'
	}

	return render(request, 'submitter/detail_submitter.html', context)

def submitted_profile(request, idArticle, submit_times):
	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'

	this_article = db.accept(104, [pre1, pre2])
	this_article = Loader.article(this_article)[0]

	idAuthor = this_article.author
	pre1 = 'id="' + idAuthor + '"'
	real_author = db.accept(122, [pre1])
	real_author = Loader.author(real_author)[0]
	this_article.author = real_author.name

	if this_article.shen1 == '已完成':
		this_article.shen1 = this_article.shen2

	context = {
		'paper': this_article,
	}

	if this_article.shen2 in ['待修改', '决定发表', '决定不发表']:

		comment_eic_path = this_article.path + 'eic_comment.txt'
		try:
			with open(comment_eic_path, 'r') as f:
				comment_eic = f.read()
		except Exception as e:
			comment_eic = ""

		if comment_eic != "":
			context['current_eic'] = True
			context['comment_eic'] = comment_eic
	
	comment_editor_path = this_article.path + 'editor_comment.txt'
	try:
		with open(comment_editor_path, 'r') as f:
			comment_editor = f.read()
	except Exception as e:
		comment_editor = ""

	if comment_editor != "":
		context['current_editor'] = True
		context['comment_editor'] = comment_editor

	if this_article.shen2 == '待修改':
		context['allow_modify'] = True

	return render(request, 'submitter/detail_submitter.html', context)

def dosubmit(request, idArticle, submit_times):
	db = Accept()

	db.accept(107, [idArticle, submit_times])

	return render(request, 'submitter/index.html', {
			'message': '提交成功，不可再修改，可在过往投稿中查看审阅状态'
		})

def deletepaper(request, idArticle, submit_times):
	db = Accept()

	pre1 = 'visible=0'
	db.accept(105, [idArticle, submit_times, pre1])

	return render(request, 'submitter/index.html', {
			'message': '删除成功'
		})

def resubmit(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	this_article = db.accept(104, [pre1, pre2])
	this_article = Loader.article(this_article)[0]

	context = {
		'form_name': '二审投稿',
		'second_submit': True,
		'old_idArticle': this_article.idArticle,
		'old_submit_times': this_article.submit_times,
		'old_path': this_article.path,
		'old_title': this_article.title,
		'old_abstract': this_article.abstract,
		'old_keywords': this_article.keywords
	}

	return render(request, 'submitter/submit.html', context)

submitter/templates/submitter/detail_submitter.html
{% extends 'paperprofile.html' %}

{% block title %}
	稿件详情
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'submitter:index' %}"><span id="profile0-tab-span">投稿人个人主页</span></a>
{% endblock %}

{% block info %}
	投稿人{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'submitter:submit' %}">投稿</a></li>
	<li><a href="{% url 'submitter:submitted' %}">过往投稿</a></li>
	<li><a href="{% url 'submitter:saved' %}">保存尚未提交</a></li>

{% endblock %}

{% block status %}
	{{ paper.shen1 }}
{% endblock %}

{% block more_information %}

	<style type="text/css">
		.detail {
			min-height: 600px;
		}
	</style>

	{% if current_eic %}

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>主编评价内容</a>
	                </div>
				</div>
			</div>
			<div class="cont">
				<p>{{ comment_eic }}</p>
			</div>
		</div>

	{% endif %}

	{% if current_editor %}

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>格式编辑评价内容</a>
	                </div>
				</div>
			</div>
			<div class="cont">
				<p>{{ comment_editor }}</p>
			</div>
		</div>

	{% endif %}

	{% if allow_change %}
		<div class="sub_back">
			<button type="button" class="button_1" onclick="doSubmit()">确认提交</button>
			<button type="button" class="button_2" onclick="">删除本文</button>
		</div>

		<form action="{% url 'submitter:dosubmit' paper.idArticle paper.submit_times %}" method="post" id="do_submit">
			{% csrf_token %}
		</form>

		<form action="{% url 'submitter:deletepaper' paper.idArticle paper.submit_times %}" method="post" id="delete_form">
			{% csrf_token %}
		</form>
	{% endif %}

	{% if allow_modify %}
		<div class="sub_back">
			<button type="button" class="button_1" onclick="reSubmit()">修改并提交</button>
		</div>

		<form action="{% url 'submitter:resubmit' paper.idArticle paper.submit_times %}" method="post" id="resubmit_form">
			{% csrf_token %}
		</form>
		
	{% endif %}

{% endblock %}

{% block script %}
	<script type="text/javascript">
		function doSubmit() {
			var form = document.getElementById('do_submit');
			form.submit();
		}
		function delete_article() {
			var form = document.getElementById('delete_form');
			form.submit();
		}
		function reSubmit() {
			var form = document.getElementById('resubmit_form');
			form.submit();
		}
	</script>
{% endblock %}

submitter/templates/submitter/index.html
{% extends 'base.html' %}

{% block title %}
	投稿人主页
{% endblock %}

{% block style %}
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'submitter:index' %}"><span id="profile0-tab-span">投稿人个人主页</span></a>
{% endblock %}

{% block info %}
	投稿人{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'submitter:submit' %}">投稿</a></li>
	<li><a href="{% url 'submitter:submitted' %}">过往投稿</a></li>
	<li><a href="{% url 'submitter:saved' %}">保存尚未提交</a></li>

{% endblock %}

{% block tab_content %}
	{% if message %}
		<div class="message">{{ message }}</div>
	{% endif %}
{% endblock %}

submitter/templates/submitter/saved.html
{% extends 'list.html' %}

{% block title %}保存尚未提交{% endblock %}

{% block t_head %}
	<tr>
		<td>题目</td>
		<td>关键词</td>
		<td>提交时间</td>
	</tr>
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'submitter:index' %}"><span id="profile0-tab-span">投稿人个人主页</span></a>
{% endblock %}

{% block info %}
	投稿人{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'submitter:submit' %}">投稿</a></li>
	<li><a href="{% url 'submitter:submitted' %}">过往投稿</a></li>
	<li><a href="{% url 'submitter:saved' %}">保存尚未提交</a></li>

{% endblock %}

{% block paper_url %}
	{% for paper in papers %}
		<tr>
			<td><a href="{% url 'submitter:profile' paper.idArticle paper.submit_times %}" class="underline">{{ paper.title }}</a></td>
			<td>{{ paper.keywords }}</td>
			<td>{{ paper.submit_time }}</td>
		</tr>
	{% endfor %}
{% endblock %}

submitter/templates/submitter/submit.html
{% extends 'newitem.html' %}

{% block title %}
	投递文章
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'submitter:index' %}">投稿人个人主页</a>
{% endblock %}

{% block info %}
	投稿人{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'submitter:submit' %}">投稿</a></li>
	<li><a href="{% url 'submitter:submitted' %}">过往投稿</a></li>
	<li><a href="{% url 'submitter:saved' %}">保存尚未提交</a></li>

{% endblock %}


{% block form %}
	<form enctype="multipart/form-data" action="{% url 'submitter:upload_file' %}" method="post" id="new-article-form" class="newitem_form" >
		{% csrf_token %}
		<input type="hidden" name="is_second_submit" value="{{ second_submit }}">
		<input type="hidden" name="old_idArticle" value="{{ old_idArticle }}">
		<input type="hidden" name="old_submit_times" value="{{ old_submit_times }}">
		<input type="hidden" name="old_path" value="{{ old_path }}">

		<div class="input_box">
	        <div class="left_text"><i class="red">*</i>文章题目</div>
	        <div class="right_input">
	            <input type="text" name="title" required="" value="{{ old_title }}" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
	        </div>
	    </div>

	    <div class="input_box">
	        <div class="left_text"><i class="red">*</i>作者</div>
	        <div class="right_input">
	            <input type="text" name="author" required="" value="" autocomplete="off" placeholder="限50字符以内。" aria-required="true">
	        </div>
	    </div>

	    <div class="input_box">
	        <div class="left_text"><i class="red">*</i>关键词</div>
	        <div class="right_input">
	            <input type="text" name="keywords" required="" value="{{ old_keywords }}" autocomplete="off" placeholder="不同领域名用空格分割" aria-required="true">
	        </div>
	    </div>

	    <div class="input_box">
	    	<div class="left_text"><i class="red">*</i>摘要</div>
	    	<div class="right_input">
	    		<textarea name="abstract" class="text_area">{{ old_abstract }}</textarea>
	    	</div>
	    </div>

	    <div class="input_box">
	    	<div class="left_text"><i class="red">*</i>附件</div>
	    	<div class="right_input">
	    		<input type="file" name="myfile">
	    	</div>
		</div>

	    <div class="sub_back">
	    	<button type="button" class="do_submit" onclick="upload()">提  交</button>
	    	<button type="button" class="return_btn" onclick="save()">保  存</button>
	    </div>
	</form>
{% endblock %}



{% block script %}
	<script type="text/javascript">
		function upload() {
			var form = document.getElementById('new-article-form');
			form.submit();
		}
		function save() {
			var form = document.getElementById('new-article-form');
			form.action = "{% url 'submitter:save_file' %}"
			form.submit();
		}
	</script>
{% endblock %}

submitter/templates/submitter/submitted.html
{% extends 'list.html' %}

{% block title %}已提交稿件{% endblock %}

{% block t_head %}
	<tr>
		<td>题目</td>
		<td>投稿次数</td>
		<td>关键词</td>
		<td>提交时间</td>
		<td>审理状态</td>
	</tr>
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'submitter:index' %}"><span id="profile0-tab-span">投稿人个人主页</span></a>
{% endblock %}

{% block info %}
	投稿人{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'submitter:submit' %}">投稿</a></li>
	<li><a href="{% url 'submitter:submitted' %}">过往投稿</a></li>
	<li><a href="{% url 'submitter:saved' %}">保存尚未提交</a></li>

{% endblock %}

{% block paper_url %}
	{% for paper in papers %}
		<tr>
			<td><a href="{% url 'submitter:submitted_profile' paper.idArticle paper.submit_times %}" class="underline">{{ paper.title }}</a></td>
			<td>{{ paper.submit_times }}</td>
			<td>{{ paper.keywords }}</td>
			<td>{{ paper.submit_time }}</td>
			<td>{{ paper.shen1 }}</td>
		</tr>
	{% endfor %}
{% endblock %}