editor/urls.py
# -*- coding: utf-8 -*-
# @Author: MarkJiYuan
# @Date:   2019-06-28 23:07:23
# @Last Modified by:   MarkJiYuan
# @email: zhengjiy16@163.com
# @Last Modified time: 2019-06-28 23:22:47
# @Abstract: 

from django.urls import path
from . import views

app_name = 'editor'
urlpatterns = [
	path('', views.index, name='index'),
	path('pending/', views.pending, name='pending'),
	path('profile/<int:idArticle>/<int:submit_times>', views.profile, name='profile'),
	path('download/<int:idArticle>/<int:submit_times>', views.download, name='download'),
	path('processing/', views.processing, name='processing'),
	path('finish/<int:idArticle>/<int:submit_times>', views.finish, name='finish'),
	path('done/', views.done, name='done')
]

papersubmission/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('reviewer/', include('reviewer.urls')),
    path('AE/', include('associateeditor.urls')),
    path('EIC/', include('editorinchief.urls')),
    path('editor/', include('editor.urls')),
	path('submitter/', include('submitter.urls')),
	path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
]

reviewer/urls.py
# -*- coding: utf-8 -*-
# @Author: MarkJiYuan
# @Date:   2019-06-28 23:16:05
# @Last Modified by:   MarkJiYuan
# @email: zhengjiy16@163.com
# @Last Modified time: 2019-06-28 23:27:14
# @Abstract: 

from django.urls import path
from . import views

app_name = 'reviewer'
urlpatterns = [
	path('', views.index, name='index'),
	path('pending', views.pending, name='pending'),
	path('profile/<int:idArticle>/<int:submit_times>', views.profile, name='profile'),
	path('download/<int:idArticle>/<int:submit_times>', views.download, name='download'),
	path('processing/', views.processing, name='processing'),
	path('finish/<int:idArticle>/<int:submit_times>', views.finish, name='finish'),
	path('done/', views.done, name='done')
]

reviewer/models.py
from django.db import models

# Create your models here.

reviewer/views.py
import os
import re
from django.shortcuts import render
from django.http import FileResponse
from paperdb.accept import Accept
from paperdb.load import Loader
from smtp.myemail import Email

def index(request):
	context = {}
	welcome = '欢迎您！专家' + request.session['username']
	return render(request, 'reviewer/index.html', {
			'message': welcome,
		})

def pending(request):
	db = Accept()

	pre1 = '审阅状态2="reviewers待审"'
	articles = db.accept(104, [pre1])
	articles = Loader.article(articles)[::-1]

	my_article = []
	for article in articles:
		if article.reviewers != None:
			incharge = article.reviewers.split('/')[0]
			if request.session['username'] in incharge:
				my_article.append(article)

	context = {
		'table_title': 'reviewer待处理',
		'papers': my_article
	}

	return render(request, 'reviewer/pending.html', context)

def processing(request):
	db = Accept()

	pre1 = '审阅状态2="reviewers正审"'
	articles = db.accept(104, [pre1])
	articles = Loader.article(articles)[::-1]

	my_article = []
	for article in articles:
		if article.reviewers != None:
			incharge = article.reviewers.split('/')[0]
			if request.session['username'] in incharge:
				my_article.append(article)

	context = {
		'table_title': 'reviewer正处理',
		'papers': my_article
	}

	return render(request, 'reviewer/pending.html', context)


def profile(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	if paper.shen2 == 'reviewers待审':
		db.accept(117, [idArticle, submit_times])

	idAuthor = paper.author
	pre1 = 'id="' + idAuthor + '"'
	real_author = db.accept(122, [pre1])
	real_author = Loader.author(real_author)[0]
	paper.author = real_author.name

	context = {
		'paper': paper,
	}

	if paper.shen2 in ['reviewers待审', 'reviewers正审']:
		context['allow_comment'] = True
	else:
		reviewer_account = request.session['username']
		reviewer = db.accept(112, ['reviewer', reviewer_account])
		reviewer = Loader.reviewer(reviewer)[0]
		current_reviewer = reviewer.name
		context['current_reviewer'] = current_reviewer

		comment_reviewer_path = paper.path + 'reviewer_' + request.session['username'] + '_comment.txt'
		try:
			with open(comment_reviewer_path, 'r') as f:
				comment_reviewer = f.read()
		except Exception as e:
			comment_reviewer = 'Reveiwer尚未提交评论'

		context['comment_reviewer'] = comment_reviewer

	return render(request, 'reviewer/detail_reviewer.html', context)


def download(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	for file_name in os.listdir(paper.path):
		answer = re.match(paper.title, file_name)
		if answer != None:
			file_path = paper.path + file_name
			break

	response = FileResponse(open(file_path, 'rb'))
	response['content_type'] = "application/octet-stream"
	response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)

	return response

def finish(request, idArticle, submit_times):

	db = Accept()

	pre1 = 'id="' + str(idArticle) + '"'
	pre2 = '投稿次数="' + str(submit_times) + '"'
	paper = db.accept(104, [pre1, pre2])
	paper = Loader.article(paper)[0]

	comment = request.POST['comment']

	comment_path = paper.path + 'reviewer_' + request.session['username'] + '_comment.txt'
	with open(comment_path, 'w') as f:
		f.write(comment)

	db.accept(118, [idArticle, submit_times])

	em = Email()
	email_context = {
		'sender_name': '迅波投审稿系统',
		'sender': 'zhengjiy16@163.com',
		'receiver_name': paper.aes,
		'receiver': 'jinsh.16@sem.tsinghua.edu.cn',
		'subject': request.session['username'] + '：已完成专家评审工作',
		'html': '<h3>尊敬的责编：您好！我已完成专家评审工作</h3><p>题目：' + paper.title + '</p>',
		'body': '系统自动通知',
		'attachments': [
		],
	}
	em.send_email(email_context)

	return render(request, 'reviewer/index.html', {
			'message': '审查结束，可在已完成中进行查看'
		})

def done(request):

	db = Accept()

	pre1 = '审阅状态2!="editor待审"'
	pre2 = '审阅状态2!="editor正审"'
	pre3 = '审阅状态2!="大boss待审"'
	pre4 = '审阅状态2!="大boss正审"'
	pre5 = '审阅状态2!="ae待审"'
	pre6 = '审阅状态2!="ae正审"'
	pre7 = '审阅状态2!="已完成"'
	pre8 = '审阅状态2!="待处理"'
	pre9 = '审阅状态2!="reviewers待审"'
	pre10 = '审阅状态2!="reviewers正审"'
	articles = db.accept(104, [pre1, pre2, pre3, pre4, pre5, pre6, pre7, pre8, pre9, pre10])
	articles = Loader.article(articles)[::-1]

	my_article = []
	for article in articles:
		print(article.reviewers)
		if article.reviewers != None:
			incharge = article.reviewers.split('/')[0]
			if request.session['username'] in incharge:
				my_article.append(article)

	context = {
		'table_title': 'reviewer已完成',
		'papers': my_article
	}

	return render(request, 'reviewer/done.html', context)

reviewer/templates/reviewer/detail_reviewer.html
{% extends 'paperprofile.html' %}

{% block title %}
	稿件详情
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'reviewer:index' %}"><span id="profile0-tab-span">专家个人主页</span></a>
{% endblock %}

{% block info %}
	专家{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'reviewer:pending' %}">待处理</a></li>
	<li><a href="{% url 'reviewer:processing' %}">处理中</a></li>
	<li><a href="{% url 'reviewer:done' %}">已完成</a></li>

{% endblock %}

{% block status %}
	{{ paper.shen2 }}
{% endblock %}

{% block more_information %}

	{% if current_reviewer %}

		<div class="info_section">
			<div class="notice">
				<div class="tit">
					<div class="crumb clearfix fl">
	                    <a>Reviewer{{ current_reviewer }}评价内容</a>
	                </div>
				</div>
			</div>
			<div class="cont">
				<p>{{ comment_reviewer }}</p>
			</div>
		</div>
		
	{% endif %}

	{% if allow_comment %}

		<div class="info_section">
	        <div class="notice">
	            <div class="tit">
	                <div class="crumb clearfix fl">
	                    <a>审阅意见</a>
	                </div>
	            </div>
	        </div>
	        <div class="cont">
	            <form action="{% url 'reviewer:finish' paper.idArticle paper.submit_times %}" method="post" id="comment-form">
	            	{% csrf_token %}
	            	<textarea name="comment" class="text_area"></textarea>

					<button type="submit" class="button_1" style="margin-top: 20px;margin-left: 50px;margin-bottom: 30px;">完成评审</button>
	            </form>
	        </div>
	    </div>

	{% endif %}
		
{% endblock %}

{% block script %}

{% endblock %}

reviewer/templates/reviewer/done.html
{% extends 'list.html' %}

{% block title %}
	{{ table_title }}
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'reviewer:index' %}">专家个人主页</a>
{% endblock %}

{% block info %}
	专家{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'reviewer:pending' %}">待处理</a></li>
	<li><a href="{% url 'reviewer:processing' %}">处理中</a></li>
	<li><a href="{% url 'reviewer:done' %}">已完成</a></li>

{% endblock %}

{% block t_head %}
	<tr>
		<td>题目</td>
		<td>关键词</td>
		<td>提交时间</td>
		<td>审阅状态2</td>
	</tr>
{% endblock %}

{% block paper_url %}
	{% for paper in papers %}
		<tr>
			<td><a href="{% url 'reviewer:profile' paper.idArticle paper.submit_times %}" class="underline">{{ paper.title }}</a></td>
			<td>{{ paper.keywords }}</td>
			<td>{{ paper.submit_time }}</td>
			<td>{{ paper.shen2 }}</td>
		</tr>
	{% endfor %}
{% endblock %}

reviewer/templates/reviewer/index.html
{% extends "base.html" %}

{% block title %}
	专家主页
{% endblock %}

{% block index_button %}
	<a class="#course1" id="profile0-tab" href="{% url 'reviewer:index' %}"><span id="profile0-tab-span">专家个人主页</span></a>
{% endblock %}

{% block info %}
	专家{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'reviewer:pending' %}">待处理</a></li>
	<li><a href="{% url 'reviewer:processing' %}">处理中</a></li>
	<li><a href="{% url 'reviewer:done' %}">已完成</a></li>

{% endblock %}

{% block tab_content %}
	{% if message %}
		<div class="message">{{ message }}</div>
	{% endif %}
{% endblock %}

reviewer/templates/reviewer/pending.html
{% extends 'list.html' %}

{% block title %}
	{{ table_title }}
{% endblock %}

{% block index_button %}
	<a class="navbar-brand" href="{% url 'reviewer:index' %}">专家个人主页</a>
{% endblock %}

{% block info %}
	专家{{ request.session.username }}
{% endblock %}

{% block content %}

	<li><a href="{% url 'reviewer:pending' %}">待处理</a></li>
	<li><a href="{% url 'reviewer:processing' %}">处理中</a></li>
	<li><a href="{% url 'reviewer:done' %}">已完成</a></li>

{% endblock %}

{% block t_head %}
	<tr>
		<td>题目</td>
		<td>关键词</td>
		<td>提交时间</td>
	</tr>
{% endblock %}

{% block paper_url %}
	{% for paper in papers %}
		<tr>
			<td><a href="{% url 'reviewer:profile' paper.idArticle paper.submit_times %}" class="underline">{{ paper.title }}</a></td>
			<td>{{ paper.keywords }}</td>
			<td>{{ paper.submit_time }}</td>
		</tr>
	{% endfor %}
{% endblock %}